---

- name: Opensips | Clone repo
  become: true
  git:
    repo: "{{ opensips_cp_repo }}"
    dest: "{{ opensips_cp_path }}"
    version: "{{ opensips_cp_cp_version }}"

- name: Opensips | Config apache
  become: true
  template:
    src: "{{ opensips_config_template_dir }}/apache2.conf.j2"
    dest: "{{ opensips_apache_dir }}/{{ item }}"
    backup: true
  with_items: "{{ opensips_apache_conf_file }}"
  notify: Restart apache2

- name: Opensips | CP file permission
  become: true
  shell: "chown -R www-data:www-data {{ opensips_cp_path }}"

- name: Opensips | Create OCP table.
  become: true
  shell: psql -h {{ opensips_db_host }} -U {{ opensips_db_root_user }} -d opensips < config/db_schema.pgsql chdir={{ opensips_cp_path }}

- name: Opensips | DB.INC config.
  become: true
  template:
    src: "{{ opensips_config_template_dir }}/db.inc.php.j2"
    dest: "{{ opensips_cp_path }}/config/db.inc.php"
    backup: true

- name: Opensips | local.inc CDR config.
  become: true
  template:
    src: "{{ opensips_config_template_dir }}/local.inc.php.j2"
    dest: "{{ opensips_cp_path }}/config/tools/system/cdrviewer/local.inc.php"
    backup: true
  notify: Restart apache2