---
- name: Restart opensips
  become: true
  service: name=opensips state=restarted

- name: Restart rsyslog
  become: true
  service: name=rsyslog state=restarted

- name: Restart apache2
  become: true
  service: name=apache2 state=restarted